"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { Select } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/components/ui/toast";
import { CustomerStatusBadge } from "@/features/customers/components/customer-status-badge";
import { useCustomers } from "@/features/customers/hooks/use-customers";
import { useDeals } from "@/features/deals/hooks/use-deals";
import { DEAL_STAGE_META, type DealStage } from "@/features/deals/types";
import { useFinance } from "@/features/finance/hooks/use-finance";
import type { PaymentMethod } from "@/features/finance/types";
import { useQuotes } from "@/features/quotes/hooks/use-quotes";
import { useProducts } from "@/features/products/hooks/use-products";
import { daysFromNow, formatDate, formatDateTime, relativeTime } from "@/features/shared/utils/date";
import { formatVnd } from "@/features/shared/utils/money";
import { useTasks } from "@/features/tasks/hooks/use-tasks";
import { Building2, ChevronLeft, CircleDollarSign, Clock3, Handshake, Mail, MapPin, Phone, Plus, ReceiptText, Send, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

export function CustomerWorkspace({ id }: { id: string }) {
  const router = useRouter(); const { toast } = useToast(); const { getById, getDebt } = useCustomers(); const customer = getById(id);
  const dealsApi = useDeals(); const deals = dealsApi.byCustomer(id); const tasks = useTasks(); const customerTasks = tasks.all.filter((task) => task.customerId === id).sort((a, b) => +new Date(a.dueAt) - +new Date(b.dueAt));
  const quotesApi = useQuotes({ customerId: id }); const quotes = quotesApi.rows; const products = useProducts().all.filter((product) => product.status === "active"); const finance = useFinance(); const invoices = finance.allInvoices.filter((invoice) => invoice.customerId === id && invoice.status !== "cancelled"); const payments = finance.payments.filter((payment) => payment.customerId === id);
  const [paymentOpen, setPaymentOpen] = useState(false); const [taskOpen, setTaskOpen] = useState(false); const [dealOpen, setDealOpen] = useState(false); const [quoteOpen, setQuoteOpen] = useState(false);
  if (!customer) return <main className="flex h-full items-center justify-center"><div className="rounded-lg border border-border bg-white p-6 text-center"><p className="font-medium">Không tìm thấy khách hàng</p><Button className="mt-3" variant="outline" onClick={() => router.push("/khach-hang")}>Quay lại danh sách</Button></div></main>;
  const debt = getDebt(id); const paidTotal = invoices.reduce((sum, invoice) => sum + invoice.paidAmount, 0); const openTasks = customerTasks.filter((task) => task.status === "open").length; const pipeline = deals.filter((deal) => deal.stage !== "won" && deal.stage !== "lost").reduce((sum, deal) => sum + deal.value, 0);
  return <main className="min-h-0 flex-1 overflow-auto bg-surface"><div className="mx-auto max-w-[1440px] p-3 lg:p-5"><button type="button" onClick={() => router.push("/khach-hang")} className="mb-3 inline-flex items-center gap-1 text-xs text-muted hover:text-foreground"><ChevronLeft className="h-3.5 w-3.5" />Khách hàng</button>
    <section className="rounded-lg border border-border bg-white"><div className="flex flex-col gap-4 p-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex min-w-0 gap-3"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg text-lg font-bold text-white" style={{ background: customer.logoColor ?? "#334155" }}>{customer.name.slice(0, 1)}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-lg font-semibold">{customer.name}</h1><CustomerStatusBadge status={customer.status} /></div><p className="mt-1 font-mono text-xs text-muted">{customer.code} · {customer.type === "company" ? "Doanh nghiệp" : "Cá nhân"}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted"><span className="inline-flex items-center gap-1"><UserRound className="h-3.5 w-3.5" />{customer.contactName || "Chưa có đầu mối"}</span><span className="inline-flex items-center gap-1"><Phone className="h-3.5 w-3.5" />{customer.phone || "—"}</span><span className="inline-flex items-center gap-1"><Mail className="h-3.5 w-3.5" />{customer.email || "—"}</span></div></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => setTaskOpen(true)}><Plus className="h-3.5 w-3.5" />Tạo việc</Button><Button variant="outline" size="sm" onClick={() => setDealOpen(true)}><Handshake className="h-3.5 w-3.5" />Tạo cơ hội</Button><Button variant="primary" size="sm" onClick={() => setPaymentOpen(true)} disabled={debt <= 0}><CircleDollarSign className="h-3.5 w-3.5" />Ghi thanh toán</Button></div></div>
      <div className="grid border-t border-border sm:grid-cols-2 xl:grid-cols-5"><Metric label="Công nợ cần thu" value={formatVnd(debt)} tone={debt > 0 ? "danger" : "default"} /><Metric label="Đã thanh toán" value={formatVnd(paidTotal)} /><Metric label="Pipeline đang mở" value={formatVnd(pipeline)} /><Metric label="Công việc cần xử lý" value={String(openTasks)} /><Metric label="Cập nhật gần nhất" value={relativeTime(customer.updatedAt)} /></div></section>
    <div className="mt-3 grid gap-3 xl:grid-cols-[minmax(0,1fr)_340px]"><section className="min-w-0 rounded-lg border border-border bg-white p-4"><Tabs defaultValue="overview"><TabsList><TabsTrigger value="overview">Tổng quan</TabsTrigger><TabsTrigger value="finance">Công nợ & thanh toán ({invoices.length})</TabsTrigger><TabsTrigger value="deals">Cơ hội ({deals.length})</TabsTrigger><TabsTrigger value="quotes">Báo giá ({quotes.length})</TabsTrigger></TabsList><TabsContent value="overview"><div className="grid gap-4 pt-3 lg:grid-cols-2"><ActivityPanel tasks={customerTasks} /><InvoicePanel invoices={invoices} /></div></TabsContent><TabsContent value="finance"><FinancePanel invoices={invoices} payments={payments} /></TabsContent><TabsContent value="deals"><div className="flex justify-end pt-3"><Button size="sm" onClick={() => setDealOpen(true)}><Plus className="h-3.5 w-3.5" />Tạo cơ hội</Button></div><DealsPanel rows={deals} onStageChange={dealsApi.setStage} /></TabsContent><TabsContent value="quotes"><div className="flex justify-end pt-3"><Button size="sm" onClick={() => setQuoteOpen(true)}><Plus className="h-3.5 w-3.5" />Tạo báo giá</Button></div><QuotesPanel rows={quotes} onApprove={quotesApi.approve} toast={toast} /></TabsContent></Tabs></section>
      <aside className="space-y-3"><section className="rounded-lg border border-border bg-white p-4"><h2 className="text-sm font-semibold">Thông tin liên hệ</h2><div className="mt-3 space-y-3 text-sm"><Info icon={UserRound} label="Phụ trách" value={customer.owner.name} /><Info icon={MapPin} label="Địa chỉ" value={customer.address || "Chưa cập nhật"} /><Info icon={Building2} label="Nguồn" value={customer.source} /></div></section><section className="rounded-lg border border-border bg-white p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Việc sắp tới</h2><button className="text-xs text-blue-700 hover:underline" onClick={() => setTaskOpen(true)}>Tạo việc</button></div><div className="mt-3 space-y-2">{customerTasks.filter((task) => task.status === "open").slice(0, 4).map((task) => <button key={task.id} type="button" className="block w-full rounded border border-border px-2.5 py-2 text-left hover:bg-muted-bg/60" onClick={() => router.push("/cong-viec")}><p className="truncate text-xs font-medium">{task.title}</p><p className="mt-1 text-[11px] text-muted">Hạn {formatDateTime(task.dueAt)} · Mở drawer từ danh sách</p></button>)}{openTasks === 0 ? <p className="text-xs text-muted">Không có công việc mở.</p> : null}</div></section><section className="rounded-lg border border-border bg-white p-4"><h2 className="text-sm font-semibold">Ghi chú nội bộ</h2><p className="mt-2 text-sm leading-relaxed text-muted">{customer.notes || "Chưa có ghi chú."}</p></section></aside></div>
    <PaymentModal open={paymentOpen} onOpenChange={setPaymentOpen} customerId={id} invoices={invoices} onSave={finance.recordPayment} toast={toast} owner={customer.owner} />
    <QuickTaskModal open={taskOpen} onOpenChange={setTaskOpen} customerId={id} owner={customer.owner} onSave={tasks.create} toast={toast} />
    <DealModal open={dealOpen} onOpenChange={setDealOpen} customerId={id} owner={customer.owner} products={products} onSave={dealsApi.create} toast={toast} />
    <QuoteModal open={quoteOpen} onOpenChange={setQuoteOpen} customerId={id} owner={customer.owner} deals={deals} products={products} onSave={quotesApi.create} toast={toast} />
  </div></main>;
}

function Metric({ label, value, tone = "default" }: { label: string; value: string; tone?: "default" | "danger" }) { return <div className="border-b border-border px-4 py-3 last:border-b-0 sm:border-r sm:last:border-r-0 xl:border-b-0"><p className="text-[11px] font-medium uppercase tracking-wide text-muted">{label}</p><p className={tone === "danger" ? "mt-1 text-base font-semibold tabular-nums text-danger" : "mt-1 text-base font-semibold tabular-nums"}>{value}</p></div>; }
function Info({ icon: Icon, label, value }: { icon: typeof MapPin; label: string; value: string }) { return <div className="flex gap-2"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-muted" /><div><p className="text-xs text-muted">{label}</p><p className="mt-0.5">{value}</p></div></div>; }
function ActivityPanel({ tasks }: { tasks: ReturnType<typeof useTasks>["all"] }) { return <section><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Hoạt động gần đây</h2><Clock3 className="h-4 w-4 text-muted" /></div><div className="mt-3 space-y-0 border-l border-border pl-3">{tasks.slice(0, 6).map((task) => <div key={task.id} className="relative pb-3 last:pb-0"><i className="absolute -left-[17px] top-1 h-2 w-2 rounded-full bg-blue-500" /><p className="text-sm font-medium">{task.title}</p><p className="mt-0.5 text-xs text-muted">{task.status === "done" ? "Đã hoàn thành" : "Hạn"} · {formatDateTime(task.dueAt)}</p></div>)}{tasks.length === 0 ? <p className="text-sm text-muted">Chưa có hoạt động.</p> : null}</div></section>; }
function InvoicePanel({ invoices }: { invoices: ReturnType<typeof useFinance>["allInvoices"] }) { return <section><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Hóa đơn cần theo dõi</h2><ReceiptText className="h-4 w-4 text-muted" /></div><div className="mt-3 overflow-hidden rounded border border-border">{invoices.slice(0, 5).map((invoice) => <div key={invoice.id} className="flex items-center justify-between gap-2 border-b border-border px-3 py-2 last:border-0"><div><p className="font-mono text-xs font-medium">{invoice.code}</p><p className="mt-0.5 text-[11px] text-muted">Hạn {formatDate(invoice.dueDate)}</p></div><div className="text-right"><p className="text-xs font-medium">{formatVnd(invoice.amount - invoice.paidAmount)}</p><Badge tone={invoice.status === "paid" ? "success" : invoice.status === "partial" ? "warning" : "danger"}>{invoice.status === "paid" ? "Đã thu" : invoice.status === "partial" ? "Thu một phần" : "Chưa thu"}</Badge></div></div>)}{invoices.length === 0 ? <p className="p-4 text-center text-sm text-muted">Chưa có hóa đơn.</p> : null}</div></section>; }
function FinancePanel({ invoices, payments }: { invoices: ReturnType<typeof useFinance>["allInvoices"]; payments: ReturnType<typeof useFinance>["payments"] }) { return <div className="pt-4"><h2 className="text-sm font-semibold">Công nợ theo hóa đơn</h2><div className="mt-3 overflow-x-auto rounded border border-border"><table className="w-full min-w-[660px] text-sm"><thead className="bg-muted-bg text-left text-xs text-muted"><tr><th className="px-3 py-2">Hóa đơn</th><th className="px-3 py-2">Hạn thanh toán</th><th className="px-3 py-2 text-right">Giá trị</th><th className="px-3 py-2 text-right">Đã thu</th><th className="px-3 py-2 text-right">Còn lại</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id} className="border-t border-border"><td className="px-3 py-2 font-mono text-xs">{invoice.code}</td><td className="px-3 py-2 text-muted">{formatDate(invoice.dueDate)}</td><td className="px-3 py-2 text-right tabular-nums">{formatVnd(invoice.amount)}</td><td className="px-3 py-2 text-right tabular-nums text-success">{formatVnd(invoice.paidAmount)}</td><td className="px-3 py-2 text-right font-medium tabular-nums text-danger">{formatVnd(invoice.amount - invoice.paidAmount)}</td></tr>)}</tbody></table></div><h2 className="mt-5 text-sm font-semibold">Lịch sử thanh toán</h2><div className="mt-3 divide-y divide-border rounded border border-border">{payments.map((payment) => <div key={payment.id} className="flex items-center justify-between gap-3 px-3 py-2"><div><p className="font-mono text-xs font-medium">{payment.code}</p><p className="mt-0.5 text-[11px] text-muted">{formatDateTime(payment.paidAt)} · {payment.note || payment.method}</p></div><span className="font-medium tabular-nums text-success">+{formatVnd(payment.amount)}</span></div>)}{payments.length === 0 ? <p className="p-4 text-center text-sm text-muted">Chưa có thanh toán được ghi nhận.</p> : null}</div></div>; }
function DealsPanel({ rows, onStageChange }: { rows: ReturnType<typeof useDeals>["all"]; onStageChange: (id: string, stage: DealStage) => unknown }) { return <div className="pt-3 space-y-2">{rows.map((deal) => <div key={deal.id} className="flex items-center justify-between gap-3 rounded border border-border px-3 py-2.5"><Link href={`/co-hoi/${deal.id}`} className="min-w-0 hover:underline"><p className="truncate text-sm font-medium">{deal.title}</p><p className="mt-0.5 text-xs text-muted">{deal.code} · {deal.probability}% xác suất</p></Link><div className="flex items-center gap-3"><Select className="h-8 w-36 text-xs" value={deal.stage} onChange={(event) => onStageChange(deal.id, event.target.value as DealStage)}>{Object.entries(DEAL_STAGE_META).map(([stage, data]) => <option key={stage} value={stage}>{data.label}</option>)}</Select><span className="shrink-0 text-sm font-semibold">{formatVnd(deal.value)}</span></div></div>)}{rows.length === 0 ? <p className="py-8 text-center text-sm text-muted">Chưa có cơ hội.</p> : null}</div>; }
function QuotesPanel({ rows, onApprove, toast }: { rows: ReturnType<typeof useQuotes>["all"]; onApprove: (id: string) => unknown; toast: ReturnType<typeof useToast>["toast"] }) { return <div className="pt-3 space-y-2">{rows.map((quote) => <div key={quote.id} className="flex items-center justify-between gap-3 rounded border border-border px-3 py-2.5"><Link href={`/bao-gia/${quote.id}`} className="min-w-0 hover:underline"><p className="text-sm font-medium">{quote.code}</p><p className="mt-0.5 text-xs text-muted">Hiệu lực đến {formatDate(quote.validUntil)}</p></Link><div className="flex items-center gap-3"><Badge tone={quote.status === "approved" ? "success" : quote.status === "draft" ? "neutral" : "warning"}>{quote.status}</Badge>{(quote.status === "draft" || quote.status === "sent") ? <Button size="sm" variant="outline" onClick={() => { try { onApprove(quote.id); toast("Đã duyệt báo giá", "success"); } catch (error) { toast(error instanceof Error ? error.message : "Không thể duyệt", "error"); } }}>Duyệt</Button> : null}<span className="shrink-0 text-sm font-semibold">{formatVnd(quote.total)}</span></div></div>)}{rows.length === 0 ? <p className="py-8 text-center text-sm text-muted">Chưa có báo giá.</p> : null}</div>; }
function PaymentModal({ open, onOpenChange, customerId, invoices, onSave, toast, owner }: { open: boolean; onOpenChange: (value: boolean) => void; customerId: string; invoices: ReturnType<typeof useFinance>["allInvoices"]; onSave: ReturnType<typeof useFinance>["recordPayment"]; toast: ReturnType<typeof useToast>["toast"]; owner: { id: string; name: string } }) { const unpaid = invoices.filter((invoice) => invoice.amount > invoice.paidAmount); const [invoiceId, setInvoiceId] = useState(""); const [amount, setAmount] = useState(0); const [method, setMethod] = useState<PaymentMethod>("bank"); const selected = unpaid.find((invoice) => invoice.id === invoiceId) ?? unpaid[0]; const currentAmount = invoiceId ? amount : selected ? selected.amount - selected.paidAmount : 0; const submit = () => { if (!selected || currentAmount <= 0 || currentAmount > selected.amount - selected.paidAmount) { toast("Kiểm tra lại hóa đơn và số tiền thanh toán", "error"); return; } onSave({ invoiceId: selected.id, customerId, amount: currentAmount, method, paidAt: new Date().toISOString(), owner, note: "Ghi nhận tại hồ sơ khách hàng" }); toast("Đã ghi nhận thanh toán", "success"); onOpenChange(false); setInvoiceId(""); setAmount(0); }; return <Modal open={open} onOpenChange={onOpenChange} title="Ghi nhận thanh toán" description="Cập nhật công nợ và lịch sử thanh toán của khách hàng" footer={<><Button variant="outline" onClick={() => onOpenChange(false)}>Hủy</Button><Button variant="primary" onClick={submit}>Xác nhận thanh toán</Button></>}><div className="grid gap-3"><label className="space-y-1 text-xs"><span className="text-muted">Hóa đơn cần thu</span><Select className="w-full" value={invoiceId || selected?.id || ""} onChange={(event) => { setInvoiceId(event.target.value); const invoice = unpaid.find((item) => item.id === event.target.value); setAmount(invoice ? invoice.amount - invoice.paidAmount : 0); }}>{unpaid.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.code} — còn {formatVnd(invoice.amount - invoice.paidAmount)}</option>)}</Select></label><label className="space-y-1 text-xs"><span className="text-muted">Số tiền nhận</span><Input type="number" min={0} value={currentAmount} onChange={(event) => setAmount(Number(event.target.value) || 0)} /></label><label className="space-y-1 text-xs"><span className="text-muted">Phương thức</span><Select className="w-full" value={method} onChange={(event) => setMethod(event.target.value as PaymentMethod)}><option value="bank">Chuyển khoản</option><option value="cash">Tiền mặt</option><option value="card">Thẻ</option><option value="other">Khác</option></Select></label></div></Modal>; }
function QuickTaskModal({ open, onOpenChange, customerId, owner, onSave, toast }: { open: boolean; onOpenChange: (value: boolean) => void; customerId: string; owner: { id: string; name: string }; onSave: ReturnType<typeof useTasks>["create"]; toast: ReturnType<typeof useToast>["toast"] }) { const [title, setTitle] = useState(""); const submit = () => { if (!title.trim()) { toast("Nhập nội dung công việc", "error"); return; } onSave({ title: title.trim(), type: "followup", status: "open", dueAt: daysFromNow(1), owner, customerId }); toast("Đã tạo công việc follow-up", "success"); setTitle(""); onOpenChange(false); }; return <Modal open={open} onOpenChange={onOpenChange} title="Tạo công việc cho khách hàng" footer={<><Button variant="outline" onClick={() => onOpenChange(false)}>Hủy</Button><Button variant="primary" onClick={submit}><Send className="h-3.5 w-3.5" />Tạo việc</Button></>}><label className="space-y-1 text-xs"><span className="text-muted">Nội dung *</span><Input autoFocus placeholder="Ví dụ: Gọi xác nhận lịch khảo sát" value={title} onChange={(event) => setTitle(event.target.value)} /></label><p className="mt-3 text-xs text-muted">Mặc định là follow-up, hạn xử lý vào ngày mai. Có thể chỉnh chi tiết tại trang Công việc.</p></Modal>; }
function DealModal({ open, onOpenChange, customerId, owner, products, onSave, toast }: { open: boolean; onOpenChange: (value: boolean) => void; customerId: string; owner: { id: string; name: string }; products: ReturnType<typeof useProducts>["all"]; onSave: ReturnType<typeof useDeals>["create"]; toast: ReturnType<typeof useToast>["toast"] }) { const [title, setTitle] = useState(""); const [value, setValue] = useState(0); const [productId, setProductId] = useState(""); const submit = () => { if (!title.trim()) { toast("Nhập tên cơ hội", "error"); return; } onSave({ title: title.trim(), customerId, stage: "new", value, owner, expectedCloseDate: daysFromNow(14), productIds: productId ? [productId] : [], notes: "Tạo từ hồ sơ khách hàng" }); toast("Đã tạo cơ hội và công việc follow-up", "success"); setTitle(""); setValue(0); setProductId(""); onOpenChange(false); }; return <Modal open={open} onOpenChange={onOpenChange} title="Tạo cơ hội mới" description="Cơ hội sẽ được liên kết trực tiếp với khách hàng này" footer={<><Button variant="outline" onClick={() => onOpenChange(false)}>Hủy</Button><Button variant="primary" onClick={submit}>Tạo cơ hội</Button></>}><div className="grid gap-3"><label className="space-y-1 text-xs"><span className="text-muted">Tên cơ hội *</span><Input autoFocus placeholder="Ví dụ: Lắp camera khu vực kho" value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="space-y-1 text-xs"><span className="text-muted">Giá trị dự kiến</span><Input type="number" min={0} value={value} onChange={(event) => setValue(Number(event.target.value) || 0)} /></label><label className="space-y-1 text-xs"><span className="text-muted">Sản phẩm chính</span><Select className="w-full" value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">Chưa chọn</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</Select></label></div></Modal>; }
function QuoteModal({ open, onOpenChange, customerId, owner, deals, products, onSave, toast }: { open: boolean; onOpenChange: (value: boolean) => void; customerId: string; owner: { id: string; name: string }; deals: ReturnType<typeof useDeals>["all"]; products: ReturnType<typeof useProducts>["all"]; onSave: ReturnType<typeof useQuotes>["create"]; toast: ReturnType<typeof useToast>["toast"] }) { const [dealId, setDealId] = useState(""); const [productId, setProductId] = useState(""); const [qty, setQty] = useState(1); const product = products.find((item) => item.id === productId); const submit = () => { if (!product) { toast("Chọn ít nhất một sản phẩm", "error"); return; } onSave({ customerId, dealId: dealId || undefined, status: "draft", validUntil: daysFromNow(15), owner, terms: "Thanh toán theo thỏa thuận", lines: [{ productId: product.id, qty, unitPrice: product.unitPrice, discountPercent: 0, vatPercent: product.vatPercent }] }); toast("Đã tạo báo giá nháp", "success"); setProductId(""); setDealId(""); setQty(1); onOpenChange(false); }; return <Modal open={open} onOpenChange={onOpenChange} title="Tạo báo giá nháp" description="Có thể thêm dòng hàng và chỉnh điều khoản chi tiết sau khi tạo" footer={<><Button variant="outline" onClick={() => onOpenChange(false)}>Hủy</Button><Button variant="primary" onClick={submit}>Tạo báo giá</Button></>}><div className="grid gap-3"><label className="space-y-1 text-xs"><span className="text-muted">Gắn với cơ hội</span><Select className="w-full" value={dealId} onChange={(event) => setDealId(event.target.value)}><option value="">Không gắn cơ hội</option>{deals.map((deal) => <option key={deal.id} value={deal.id}>{deal.code} — {deal.title}</option>)}</Select></label><label className="space-y-1 text-xs"><span className="text-muted">Sản phẩm *</span><Select className="w-full" value={productId} onChange={(event) => setProductId(event.target.value)}><option value="">Chọn sản phẩm</option>{products.map((item) => <option key={item.id} value={item.id}>{item.name} — {formatVnd(item.unitPrice)}</option>)}</Select></label><label className="space-y-1 text-xs"><span className="text-muted">Số lượng</span><Input type="number" min={1} value={qty} onChange={(event) => setQty(Math.max(1, Number(event.target.value) || 1))} /></label>{product ? <p className="rounded border border-border bg-muted-bg/50 px-3 py-2 text-xs">Tạm tính: <strong>{formatVnd(product.unitPrice * qty * (1 + product.vatPercent / 100))}</strong> (đã gồm VAT)</p> : null}</div></Modal>; }
