"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { formatVnd } from "@/features/shared/utils/money";
import { loadOwners } from "@/features/shared/api/owners";
import { apiFetch, toQuery } from "@/lib/api-client";

type Ref = { id: string; name: string };
type Report = { summary: { grossRevenue: number; reductions: number; netRevenue: number; cogs: number; laborCost: number; otherExpenses: number; profit: number; receivable: number }; customers: { customerId: string; revenue: number; cogs: number; paid: number; receivable: number }[] };
const today = new Date().toISOString().slice(0, 10);

export function FinanceReportsPanel() {
  const [filters, setFilters] = useState({ from: today.slice(0, 4) + "-01-01", to: today, customerId: "", employeeId: "", projectId: "" });
  const [customers, setCustomers] = useState<Ref[]>([]); const [employees, setEmployees] = useState<Ref[]>([]); const [projects, setProjects] = useState<Ref[]>([]); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [result, cs, us, ps] = await Promise.all([apiFetch<Report>(`/api/v1/finance/reports${toQuery(filters)}`), apiFetch<Ref[]>(`/api/v1/customers${toQuery({ pageSize: 100, status: "active" })}`), loadOwners(), apiFetch<Ref[]>(`/api/v1/projects${toQuery({ pageSize: 100 })}`)]); setReport(result.data); setCustomers(cs.data ?? []); setEmployees(us); setProjects(ps.data ?? []); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, [load]);
  function exportCsv() { if (!report) return; const lines = [["Chỉ tiêu", "Số tiền"], ["Doanh thu gộp", report.summary.grossRevenue], ["Giảm trừ", report.summary.reductions], ["Doanh thu thuần", report.summary.netRevenue], ["Giá vốn", report.summary.cogs], ["Chi phí nhân công", report.summary.laborCost], ["Chi phí khác", report.summary.otherExpenses], ["Lợi nhuận tạm tính", report.summary.profit], ["Công nợ", report.summary.receivable]].map((row) => row.join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\uFEFF" + lines], { type: "text/csv;charset=utf-8" })); link.download = "bao-cao-tai-chinh.csv"; link.click(); URL.revokeObjectURL(link.href); }
  const s = report?.summary;
  return <div className="flex-1 overflow-auto p-5"><div className="mb-4 flex flex-wrap gap-2"><Input className="w-36" type="date" value={filters.from} onChange={(e) => setFilters((x) => ({ ...x, from: e.target.value }))} /><Input className="w-36" type="date" value={filters.to} onChange={(e) => setFilters((x) => ({ ...x, to: e.target.value }))} /><Lookup label="Khách hàng" rows={customers} value={filters.customerId} onChange={(customerId) => setFilters((x) => ({ ...x, customerId }))} /><Lookup label="Nhân viên" rows={employees} value={filters.employeeId} onChange={(employeeId) => setFilters((x) => ({ ...x, employeeId }))} /><Lookup label="Công trình" rows={projects} value={filters.projectId} onChange={(projectId) => setFilters((x) => ({ ...x, projectId }))} /><Button variant="outline" onClick={exportCsv} disabled={!s}>Xuất CSV</Button></div>{loading || !s ? <p className="text-sm text-muted">Đang tổng hợp báo cáo...</p> : <><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Doanh thu gộp",s.grossRevenue],["Giảm trừ",s.reductions],["Doanh thu thuần",s.netRevenue],["Giá vốn",s.cogs],["Chi phí nhân công",s.laborCost],["Chi phí khác",s.otherExpenses],["Lợi nhuận tạm tính",s.profit],["Công nợ",s.receivable]].map(([label,value]) => <div className="rounded-md border border-border bg-white p-4" key={String(label)}><p className="text-xs text-muted">{label}</p><p className="mt-1 text-lg font-semibold">{formatVnd(Number(value))}</p></div>)}</div><table className="mt-5 w-full text-sm"><thead className="border-b text-left text-xs text-muted"><tr><th className="p-2">Khách hàng</th><th className="p-2 text-right">Doanh thu</th><th className="p-2 text-right">Giá vốn</th><th className="p-2 text-right">Đã thu</th><th className="p-2 text-right">Công nợ</th></tr></thead><tbody>{report.customers.map((row) => <tr className="border-b" key={row.customerId}><td className="p-2">{customers.find((c) => c.id === row.customerId)?.name ?? row.customerId}</td><td className="p-2 text-right">{formatVnd(row.revenue)}</td><td className="p-2 text-right">{formatVnd(row.cogs)}</td><td className="p-2 text-right">{formatVnd(row.paid)}</td><td className="p-2 text-right">{formatVnd(row.receivable)}</td></tr>)}</tbody></table></>}</div>;
}
function Lookup({ label, rows, value, onChange }: { label: string; rows: Ref[]; value: string; onChange: (value: string) => void }) { return <Select className="w-44" value={value} onChange={(e) => onChange(e.target.value)}><option value="">{label}: tất cả</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</Select>; }
