"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/ui/empty-state";
import { Input } from "@/components/ui/input";
import { Modal } from "@/components/ui/modal";
import { Select } from "@/components/ui/select";
import { useToast } from "@/components/ui/toast";
import { useCurrentUser } from "@/features/auth/hooks/use-current-user";
import { useOwners } from "@/features/shared/api/owners";
import { useListPage } from "@/features/shared/hooks/use-list-page";
import { formatVnd } from "@/features/shared/utils/money";
import { apiFetch, toQuery } from "@/lib/api-client";

type Ref = { id: string; name: string; code?: string; sku?: string; customerId?: string };
type Entry = { id: string; code: string; occurredAt: string; customerId: string; projectId?: string | null; productId: string; employeeId?: string | null; invoiceId?: string | null; businessType: string; totalAmount: number | string; costAmount: number | string; paymentStatus: string; paidAmount: number | string };
type Reduction = { id: string; revenueEntryId?: string | null; amount: number | string };
const TYPES = { new_construction: "Công trình mới", repair: "Sửa chữa", warranty: "Bảo hành", retail: "Bán buôn / bán lẻ" };
const REDUCTION_TYPES = { discount: "Chiết khấu", return: "Hàng trả lại", other: "Khác" };
const today = () => new Date().toISOString().slice(0, 10);

export function RevenueEntriesPanel() {
  const { toast } = useToast(); const { canCreate, canEdit } = useCurrentUser(); const list = useListPage(); const owners = useOwners();
  const [rows, setRows] = useState<Entry[]>([]); const [reductions, setReductions] = useState<Reduction[]>([]); const [customers, setCustomers] = useState<Ref[]>([]); const [products, setProducts] = useState<Ref[]>([]); const [projects, setProjects] = useState<Ref[]>([]); const [invoices, setInvoices] = useState<Ref[]>([]);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [reductionOpen, setReductionOpen] = useState(false);
  const [filters, setFilters] = useState({ from: "", to: "", customerId: "", employeeId: "", projectId: "" }); const [form, setForm] = useState(blankForm); const [reduction, setReduction] = useState(blankReduction);
  const reload = useCallback(async () => { setLoading(true); try {
    const [entries, rs, cs, ps, prs, invs] = await Promise.all([
      apiFetch<Entry[]>(`/api/v1/revenue-entries${toQuery({ pageSize: 100 })}`), apiFetch<Reduction[]>(`/api/v1/revenue-reductions${toQuery({ pageSize: 100 })}`), apiFetch<Ref[]>(`/api/v1/customers${toQuery({ pageSize: 100, status: "active" })}`), apiFetch<Ref[]>(`/api/v1/products${toQuery({ pageSize: 100, status: "active" })}`), apiFetch<Ref[]>(`/api/v1/projects${toQuery({ pageSize: 100 })}`), apiFetch<Array<{ id: string; code: string; customerId: string; status: string }>>(`/api/v1/invoices${toQuery({ pageSize: 100 })}`),
    ]);
    setRows(entries.data ?? []); setReductions(rs.data ?? []); setCustomers(cs.data ?? []); setProducts(ps.data ?? []); setProjects(prs.data ?? []); setInvoices((invs.data ?? []).filter((x) => x.status !== "cancelled").map((x) => ({ ...x, name: x.code })));
  } catch (error) { toast(error instanceof Error ? error.message : "Không thể tải chi tiết doanh thu", "error"); } finally { setLoading(false); } }, [toast]);
  useEffect(() => { void reload(); }, [reload]);
  const visibleRows = useMemo(() => rows.filter((row) => (!filters.from || row.occurredAt >= filters.from) && (!filters.to || row.occurredAt <= filters.to) && (!filters.customerId || row.customerId === filters.customerId) && (!filters.employeeId || row.employeeId === filters.employeeId) && (!filters.projectId || row.projectId === filters.projectId)), [rows, filters]);
  const summary = useMemo(() => visibleRows.reduce((total, row) => { const reduced = reductions.filter((x) => x.revenueEntryId === row.id).reduce((sum, x) => sum + Number(x.amount), 0); total.revenue += Number(row.totalAmount) - reduced; total.cogs += Number(row.costAmount); total.debt += Number(row.totalAmount) - Number(row.paidAmount); return total; }, { revenue: 0, cogs: 0, debt: 0 }), [visibleRows, reductions]);
  const selectedProjects = projects.filter((x) => !form.customerId || x.customerId === form.customerId); const selectedInvoices = invoices.filter((x) => !form.customerId || x.customerId === form.customerId);
  const change = (key: string, value: string) => setForm((old) => ({ ...old, [key]: value }));
  async function save() { if (!form.customerId || !form.productId || Number(form.qty) <= 0 || Number(form.unitPrice) < 0) return toast("Chọn khách hàng, hàng hóa/dịch vụ và nhập số liệu hợp lệ", "error"); setSaving(true); try { await apiFetch("/api/v1/revenue-entries", { method: "POST", body: JSON.stringify({ ...form, projectId: form.projectId || undefined, employeeId: form.employeeId || undefined, invoiceId: form.invoiceId || undefined, documentCode: form.documentCode || undefined, qty: Number(form.qty), unitPrice: Number(form.unitPrice), vatPercent: Number(form.vatPercent), costAmount: Number(form.costAmount), paidAmount: Number(form.paidAmount), note: form.note || undefined }) }); toast("Đã ghi chi tiết doanh thu", "success"); list.setCreateOpen(false); await reload(); } catch (error) { toast(error instanceof Error ? error.message : "Không thể ghi doanh thu", "error"); } finally { setSaving(false); } }
  async function saveReduction() { if (Number(reduction.amount) <= 0) return toast("Nhập số tiền giảm trừ lớn hơn 0", "error"); setSaving(true); try { await apiFetch("/api/v1/revenue-reductions", { method: "POST", body: JSON.stringify({ ...reduction, amount: Number(reduction.amount), note: reduction.note || undefined }) }); toast("Đã ghi khoản giảm trừ", "success"); setReductionOpen(false); await reload(); } catch (error) { toast(error instanceof Error ? error.message : "Không thể ghi giảm trừ", "error"); } finally { setSaving(false); } }
  async function updatePayment(row: Entry) { const value = window.prompt("Nhập tổng số tiền đã thu cho phát sinh này", String(row.paidAmount)); if (value === null) return; const paidAmount = Number(value); if (!Number.isFinite(paidAmount) || paidAmount < 0) return toast("Số tiền thanh toán không hợp lệ", "error"); setSaving(true); try { await apiFetch(`/api/v1/revenue-entries/${row.id}/payment`, { method: "PATCH", body: JSON.stringify({ paidAmount }) }); toast("Đã cập nhật thanh toán", "success"); await reload(); } catch (error) { toast(error instanceof Error ? error.message : "Không thể cập nhật thanh toán", "error"); } finally { setSaving(false); } }
  return <div className="flex h-full min-h-0 flex-col">
    <div className="flex flex-wrap gap-2 border-b border-border px-5 py-3"><Input className="w-36" type="date" value={filters.from} aria-label="Từ ngày" onChange={(e) => setFilters((x) => ({ ...x, from: e.target.value }))} /><Input className="w-36" type="date" value={filters.to} aria-label="Đến ngày" onChange={(e) => setFilters((x) => ({ ...x, to: e.target.value }))} /><FilterSelect label="Khách hàng" value={filters.customerId} rows={customers} onChange={(customerId) => setFilters((x) => ({ ...x, customerId }))} /><FilterSelect label="Nhân viên" value={filters.employeeId} rows={owners} onChange={(employeeId) => setFilters((x) => ({ ...x, employeeId }))} /><FilterSelect label="Công trình" value={filters.projectId} rows={projects} onChange={(projectId) => setFilters((x) => ({ ...x, projectId }))} /></div>
    <div className="grid grid-cols-1 gap-3 border-b border-border p-5 sm:grid-cols-3"><Summary label="Doanh thu sau giảm trừ" value={summary.revenue} /><Summary label="Giá vốn" value={summary.cogs} /><Summary label="Công nợ còn lại" value={summary.debt} /></div>
    <div className="flex-1 overflow-auto p-5">{!loading && !rows.length ? <EmptyState title="Chưa có phát sinh doanh thu" description="Ghi từng hàng hóa hoặc dịch vụ phát sinh để tổng hợp tài chính chính xác." action={canCreate("finance") ? <Button variant="primary" onClick={() => { setForm(blankForm()); list.setCreateOpen(true); }}>Ghi doanh thu</Button> : undefined} /> : <table className="w-full text-sm"><thead className="border-b text-left text-xs text-muted"><tr><th className="p-2">Mã</th><th className="p-2">Ngày</th><th className="p-2">Khách hàng</th><th className="p-2">Hàng hóa/DV</th><th className="p-2">Nhân viên</th><th className="p-2">Nghiệp vụ</th><th className="p-2 text-right">Tổng thu</th><th className="p-2">Thanh toán</th><th className="p-2" /></tr></thead><tbody>{visibleRows.map((row) => <tr key={row.id} className="border-b border-border/70"><td className="p-2 font-mono">{row.code}</td><td className="p-2">{row.occurredAt}</td><td className="p-2">{findName(customers, row.customerId)}</td><td className="p-2">{findName(products, row.productId)}</td><td className="p-2">{owners.find((x) => x.id === row.employeeId)?.name ?? "—"}</td><td className="p-2">{TYPES[row.businessType as keyof typeof TYPES] ?? row.businessType}</td><td className="p-2 text-right">{formatVnd(Number(row.totalAmount))}</td><td className="p-2">{paymentLabel(row.paymentStatus)}</td><td className="p-2"><div className="flex gap-2">{canCreate("finance") ? <Button size="sm" variant="outline" onClick={() => { setReduction({ ...blankReduction(), customerId: row.customerId, revenueEntryId: row.id }); setReductionOpen(true); }}>Giảm trừ</Button> : null}{!row.invoiceId && canEdit("finance", row.employeeId) ? <Button size="sm" variant="outline" onClick={() => void updatePayment(row)}>Cập nhật thu</Button> : null}</div></td></tr>)}</tbody></table>}</div>
    <Modal open={list.createOpen} onOpenChange={(value) => !saving && list.setCreateOpen(value)} title="Ghi chi tiết doanh thu" size="xl" footer={<><Button variant="outline" disabled={saving} onClick={() => list.setCreateOpen(false)}>Hủy</Button><Button variant="primary" disabled={saving} onClick={() => void save()}>{saving ? "Đang lưu..." : "Lưu"}</Button></>}><div className="grid grid-cols-2 gap-3"><Field label="Ngày phát sinh" type="date" value={form.occurredAt} onChange={(v) => change("occurredAt", v)} /><FormSelect label="Khách hàng *" value={form.customerId} rows={customers} onChange={(customerId) => setForm((x) => ({ ...x, customerId, projectId: "", invoiceId: "" }))} /><FormSelect label="Hóa đơn liên kết" value={form.invoiceId} rows={selectedInvoices} onChange={(v) => change("invoiceId", v)} /><FormSelect label="Công trình" value={form.projectId} rows={selectedProjects} onChange={(v) => change("projectId", v)} /><FormSelect label="Hàng hóa / dịch vụ *" value={form.productId} rows={products} onChange={(v) => change("productId", v)} /><FormSelect label="Nhân viên" value={form.employeeId} rows={owners} onChange={(v) => change("employeeId", v)} /><Field label="Mã phiếu" value={form.documentCode} onChange={(v) => change("documentCode", v)} /><Choice label="Loại nghiệp vụ" value={form.businessType} rows={TYPES} onChange={(v) => change("businessType", v)} /><Field label="Số lượng *" type="number" value={form.qty} onChange={(v) => change("qty", v)} /><Field label="Đơn giá *" type="number" value={form.unitPrice} onChange={(v) => change("unitPrice", v)} /><Field label="VAT (%)" type="number" value={form.vatPercent} onChange={(v) => change("vatPercent", v)} /><Field label="Giá vốn" type="number" value={form.costAmount} onChange={(v) => change("costAmount", v)} /><Choice label="Trạng thái thanh toán" value={form.paymentStatus} rows={{ unpaid: "Chưa thanh toán", partial: "Một phần", paid: "Đã thanh toán" }} onChange={(v) => change("paymentStatus", v)} /><Field label="Đã thanh toán" type="number" value={form.paidAmount} onChange={(v) => change("paidAmount", v)} /><Field label="Ghi chú" value={form.note} onChange={(v) => change("note", v)} /></div></Modal>
    <Modal open={reductionOpen} onOpenChange={(value) => !saving && setReductionOpen(value)} title="Ghi giảm trừ doanh thu" footer={<><Button variant="outline" disabled={saving} onClick={() => setReductionOpen(false)}>Hủy</Button><Button variant="primary" disabled={saving} onClick={() => void saveReduction()}>{saving ? "Đang lưu..." : "Lưu"}</Button></>}><div className="space-y-3"><Field label="Ngày phát sinh" type="date" value={reduction.occurredAt} onChange={(occurredAt) => setReduction((x) => ({ ...x, occurredAt }))} /><Choice label="Loại giảm trừ" value={reduction.type} rows={REDUCTION_TYPES} onChange={(type) => setReduction((x) => ({ ...x, type }))} /><Field label="Số tiền *" type="number" value={reduction.amount} onChange={(amount) => setReduction((x) => ({ ...x, amount }))} /><Field label="Ghi chú" value={reduction.note} onChange={(note) => setReduction((x) => ({ ...x, note }))} /></div></Modal>
  </div>;
}
function blankForm() { return { occurredAt: today(), customerId: "", projectId: "", productId: "", employeeId: "", invoiceId: "", documentCode: "", businessType: "retail", qty: "1", unitPrice: "", vatPercent: "0", costAmount: "0", paymentStatus: "unpaid", paidAmount: "0", note: "" }; }
function blankReduction() { return { occurredAt: today(), customerId: "", revenueEntryId: "", type: "discount", amount: "", note: "" }; }
function findName(rows: Ref[], id: string) { return rows.find((x) => x.id === id)?.name ?? "—"; }
function paymentLabel(status: string) { return ({ unpaid: "Chưa thanh toán", partial: "Một phần", paid: "Đã thanh toán" } as Record<string, string>)[status] ?? status; }
function Summary({ label, value }: { label: string; value: number }) { return <div className="rounded-md border border-border px-4 py-3"><p className="text-xs text-muted">{label}</p><p className="mt-1 text-lg font-semibold">{formatVnd(value)}</p></div>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className="space-y-1 text-xs"><span className="text-muted">{label}</span><Input type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function FormSelect({ label, value, rows, onChange }: { label: string; value: string; rows: Array<Ref | { id: string; name: string }>; onChange: (value: string) => void }) { return <label className="space-y-1 text-xs"><span className="text-muted">{label}</span><Select value={value} onChange={(e) => onChange(e.target.value)}><option value="">Chọn</option>{rows.map((row) => <option key={row.id} value={row.id}>{("code" in row ? row.code : undefined) ?? ("sku" in row ? row.sku : undefined) ? `${("code" in row ? row.code : undefined) ?? ("sku" in row ? row.sku : undefined)} — ` : ""}{row.name}</option>)}</Select></label>; }
function FilterSelect({ value, label, rows, onChange }: { value: string; label: string; rows: Array<Ref | { id: string; name: string }>; onChange: (value: string) => void }) { return <Select className="w-44" value={value} aria-label={label} onChange={(e) => onChange(e.target.value)}><option value="">{label}: tất cả</option>{rows.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</Select>; }
function Choice({ label, value, rows, onChange }: { label: string; value: string; rows: Record<string, string>; onChange: (value: string) => void }) { return <label className="space-y-1 text-xs"><span className="text-muted">{label}</span><Select value={value} onChange={(e) => onChange(e.target.value)}>{Object.entries(rows).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</Select></label>; }
